import { Item } from "../api";

export type MerchantActivity = {
  pk?: number;
  name?: string;
  value?: string;
};
export type MerchantType = {
  pk: number;
  class_name: string;
  provider_id: number | null;
  namespace_id: number | null;
  bank: Item;
  status: Item;
  bank_merchant_id: number | null;
  merchant_type: Item;
  merchant_rating: Item;
  company_name: string | null;
  company_name_short: string | null;
  company_state_certification_no: string | null;
  company_register_no: string | null;
  company_type: string | null;
  person_first_name: string | null;
  person_last_name: string | null;
  person_register_no: string | null;
  person_nationality: string | null;
  name_latin: string | null;
  business_type: string | null;
  merchant_activity: Item;
  merchant_business_started_date: string | null;
  daily_customer_number: number | null;
  monthly_average_revenue: string;
  phone_1: string | null;
  phone_2: string | null;
  phone_sms: string | null;
  email: string | null;
  city: Item;
  district: Item;
  quarter: Item;
  address: string | null;
  intl_card_allowed: boolean;
  is_bigger_merchant: boolean;
  image_path: string | null;
  temp_account: string | null;
  is_shop_created: boolean;
  alipay_settlement_account: string | null;
  merchant_fee: string;
  fee_percentage: string;
  provider_fee: string;
  databank_fee: string;
  intl_merchant_fee: string;
  intl_fee_percentage: string;
  intl_provider_fee: string;
  intl_databank_fee: string;
  daily_limit: number | null;
  one_time_limit: number | null;
  intl_daily_limit: number | null;
  intl_one_time_max_limit: number | null;
  intl_one_time_min_limit: number | null;
  original_request_id: string | null;
};
